/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

import logica.*;
import controlador.*;

/**
 *
 * @author jdtorres
 */
public class AgregarPaciente extends javax.swing.JFrame {

    ControladorPaciente controladorPaciente;
    Usuario usuarioActual;
    InterfazEnfermera ventanaEnfermera;

    /**
     * Creates new form AgregarPaciente
     */
    public AgregarPaciente() {
        initComponents();

    }

    public AgregarPaciente(Usuario usuario) {
        initComponents();
        controladorPaciente = new ControladorPaciente();
        usuarioActual = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        idPaciente = new javax.swing.JTextField();
        nombrePaciente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        direccionPaciente = new javax.swing.JTextField();
        telefonoPaciente = new javax.swing.JTextField();
        actividadPaciente = new javax.swing.JTextField();
        epsPaciente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        fechaPaciente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        atrasB = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Identificación");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));
        getContentPane().add(idPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 60, 126, -1));
        getContentPane().add(nombrePaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 86, 126, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));
        getContentPane().add(direccionPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 117, 126, -1));
        getContentPane().add(telefonoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 148, 126, -1));
        getContentPane().add(actividadPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 200, 126, -1));
        getContentPane().add(epsPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 232, 126, -1));

        jLabel4.setText("Direccion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        jLabel6.setText("Actividad económica");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 203, -1, -1));

        jLabel7.setText("Seguridad social");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));
        getContentPane().add(fechaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 174, 126, -1));

        jLabel8.setText("Fecha nacimiento");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/secretary.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 90));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/teacher.png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 60, 70));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/employee (4).png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, 70));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Agregar paciente");

        atrasB.setText("Atras");
        atrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addComponent(atrasB)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(atrasB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/drugs.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 60, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/band-aid (1).png"))); // NOI18N
        jLabel13.setToolTipText("");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 50, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/care.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/fondo-blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            Paciente p = new Paciente();
            p.setIdentifiacacionPaciente(Integer.valueOf(idPaciente.getText()));
            p.setNombre(nombrePaciente.getText());
            p.setDireccion(direccionPaciente.getText());
            p.setTelefono(telefonoPaciente.getText());
            p.setFechaNacimiento(fechaPaciente.getText());
            p.setActividadEconomica(actividadPaciente.getText());
            p.setSeguridadSocial(epsPaciente.getText());
            boolean resultado = controladorPaciente.agregarPaciente(p);
            if (resultado) {
                //Icon m = new ImageIcon(getClass().getResource("/gui/images/adduser.png"));
                JOptionPane.showMessageDialog(this, "Se agrego el paciente a la base de datos", "", JOptionPane.INFORMATION_MESSAGE, null);
                limpiar();

            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al agregar el paciente", "", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void atrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBActionPerformed
        // TODO add your handling code here:
        ventanaEnfermera = new InterfazEnfermera(usuarioActual);
        ventanaEnfermera.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasBActionPerformed

    private void limpiar(){
        idPaciente.setText("");
        nombrePaciente.setText("");
        direccionPaciente.setText("");
        telefonoPaciente.setText("");
        fechaPaciente.setText("");
        actividadPaciente.setText("");
        epsPaciente.setText("");
    }
    private boolean validar() {
        boolean resultado = true;
        if (idPaciente.getText().equals("") || nombrePaciente.getText().equals("") || direccionPaciente.getText().equals("") || telefonoPaciente.getText().equals("") || fechaPaciente.getText().equals("") || actividadPaciente.getText().equals("") || epsPaciente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }
        if (!isNumeric(idPaciente.getText())) {
            JOptionPane.showMessageDialog(this, "La identificacion del paciente debe ser un dato numerico", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }
        if (!isNumeric(telefonoPaciente.getText())) {
            JOptionPane.showMessageDialog(this, "El telefono del paciente debe ser un dato numerico", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }
        
        return resultado;
    }

    private boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actividadPaciente;
    private javax.swing.JButton atrasB;
    private javax.swing.JTextField direccionPaciente;
    private javax.swing.JTextField epsPaciente;
    private javax.swing.JTextField fechaPaciente;
    private javax.swing.JTextField idPaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombrePaciente;
    private javax.swing.JTextField telefonoPaciente;
    // End of variables declaration//GEN-END:variables
}
