/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import logica.*;
import controlador.*;
import javax.swing.JOptionPane;

/**
 *
 * @author jdtorres
 */
public class AgregarMedicamentos extends javax.swing.JFrame {
    InterfazAdministrador ventanaAdmin;
    ControladorMedicamento controladorMedicamento;
    Usuario usuarioActual;

    /**
     * Creates new form AgregarMedicamentos
     */
    public AgregarMedicamentos() {
        initComponents();
        controladorMedicamento = new ControladorMedicamento();
    }

    public AgregarMedicamentos(Usuario u) {
        initComponents();
        usuarioActual = u;
        controladorMedicamento = new ControladorMedicamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idMedicamento = new javax.swing.JTextField();
        nombreMedicamento = new javax.swing.JTextField();
        descripcionM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        agregarB = new javax.swing.JButton();
        costoB = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantidadB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        atrasB = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(idMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 67, 91, -1));
        getContentPane().add(nombreMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 98, 91, -1));
        getContentPane().add(descripcionM, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 129, 91, 72));

        jLabel2.setText("Codigo medicamento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 70, -1, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 101, -1, -1));

        jLabel4.setText("Descripcion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        agregarB.setText("Agregar");
        agregarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarBActionPerformed(evt);
            }
        });
        getContentPane().add(agregarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 266, -1, -1));
        getContentPane().add(costoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 207, 91, -1));

        jLabel5.setText("Costo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 210, -1, -1));
        getContentPane().add(cantidadB, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 238, 91, -1));

        jLabel6.setText("Cantidad");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/pill.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 70, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/medicines.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 70, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/medicine.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 70, 70));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/pills (2).png"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/tablets.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 70));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Agregar medicamentos");

        atrasB.setText("Atras");
        atrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(atrasB)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(atrasB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/fondo-blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarBActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            Medicamento m = new Medicamento();
            m.setCodigo_medicamento(Integer.valueOf(idMedicamento.getText()));
            m.setNombre(nombreMedicamento.getText());
            m.setDescripcion(descripcionM.getText());
            m.setCosto(Integer.valueOf(costoB.getText()));
            m.setCantidad(Integer.valueOf(cantidadB.getText()));
            boolean resultado = controladorMedicamento.agregarMedicamento(m);
            if (resultado) {

                JOptionPane.showMessageDialog(this, "Se agrego el medicamento a la base de datos", "", JOptionPane.INFORMATION_MESSAGE, null);
                limpiar();

            } else {
                JOptionPane.showMessageDialog(this, "Hubo un error al agregar el medicamento", "", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_agregarBActionPerformed

    private void atrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBActionPerformed
        // TODO add your handling code here:
        ventanaAdmin = new InterfazAdministrador(usuarioActual);
        ventanaAdmin.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasBActionPerformed

    private void limpiar() {
        idMedicamento.setText("");
        nombreMedicamento.setText("");
        descripcionM.setText("");
        costoB.setText("");
        cantidadB.setText("");
    }

    private boolean validar() {
        boolean resultado = true;

        if (idMedicamento.getText().equals("") || nombreMedicamento.getText().equals("") || descripcionM.getText().equals("") || costoB.getText().equals("") || cantidadB.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }

        if (!isNumeric(idMedicamento.getText())) {
            JOptionPane.showMessageDialog(this, "La identificacion del medicamento debe ser un dato numerico", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }
        if (!isNumeric(costoB.getText())) {
            JOptionPane.showMessageDialog(this, "El costo del medicamento debe ser un dato numerico", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }
        if (!isNumeric(cantidadB.getText())) {
            JOptionPane.showMessageDialog(this, "La cantidad de medicamento por dosis debe ser un dato numerico", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }
        return resultado;
    }

    private boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMedicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMedicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarB;
    private javax.swing.JButton atrasB;
    private javax.swing.JTextField cantidadB;
    private javax.swing.JTextField costoB;
    private javax.swing.JTextField descripcionM;
    private javax.swing.JTextField idMedicamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreMedicamento;
    // End of variables declaration//GEN-END:variables
}
