/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.*;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import logica.*;

/**
 *
 * @author jdtorres
 */
public class Formular extends javax.swing.JFrame { //https://www.youtube.com/watch?v=QK9zwfugDxU 

    ControladorMedicamento controladorMedicamento;
    ControladorFormula controladorFormula;
    ControladorFormulaMedicamento controladorFormulaMedicamento;
    InterfazMedico ventanaMedico;
    ArrayList<FormulaMedicamento> medicamentosS;
    TableRowSorter<TableModel> sorter1;
    DefaultTableModel modelo;
    Usuario usuarioActual;
    ControladorPaciente controladorPaciente;

    /**
     * Creates new form Formular
     */
    public Formular() {
        initComponents();
        controladorFormula = new ControladorFormula();
        controladorMedicamento = new ControladorMedicamento();
        medicamentosS = new ArrayList<FormulaMedicamento>();

        modelo = (DefaultTableModel) tableM.getModel();
        modelo.setRowCount(0);

        medicamentoCB.removeAllItems();
        ArrayList<Medicamento> me = new ArrayList<Medicamento>();
        me = controladorMedicamento.consultarMedicamentos();
        medicamentoCB.addItem("");
        for (int i = 0; i < me.size(); i++) {

            String item;
            item = String.valueOf(me.get(i).getCodigo_medicamento()) + "-" + me.get(i).getNombre();
            medicamentoCB.addItem(item);

        }
    }

    public Formular(Usuario usuario) {
        initComponents();
        usuarioActual = usuario;
        controladorFormula = new ControladorFormula();
        controladorFormulaMedicamento = new ControladorFormulaMedicamento();
        controladorMedicamento = new ControladorMedicamento();
        medicamentosS = new ArrayList<FormulaMedicamento>();
        controladorPaciente = new ControladorPaciente();

        modelo = (DefaultTableModel) tableM.getModel();
        modelo.setRowCount(0);

        medicamentoCB.removeAllItems();
        ArrayList<Medicamento> me = new ArrayList<Medicamento>();
        me = controladorMedicamento.consultarMedicamentos();
        medicamentoCB.addItem("");
        for (int i = 0; i < me.size(); i++) {

            String item;
            item = String.valueOf(me.get(i).getCodigo_medicamento()) + "-" + me.get(i).getNombre();
            medicamentoCB.addItem(item);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicamentoCB = new javax.swing.JComboBox<>();
        agregarMB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableM = new javax.swing.JTable();
        idPaciente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cantidadM = new javax.swing.JTextField();
        insertarB = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        atrasB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        medicamentoCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(medicamentoCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 108, 97, -1));

        agregarMB.setText("Agregar");
        agregarMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMBActionPerformed(evt);
            }
        });
        getContentPane().add(agregarMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 107, -1, -1));

        tableM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo medicamento", "Nombre", "Descripcion", "Costo", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableM);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 148, 375, 108));
        getContentPane().add(idPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 58, 91, -1));

        jLabel2.setText("Identificacion paciente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 61, -1, -1));
        getContentPane().add(cantidadM, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 108, 37, -1));

        insertarB.setText("Terminar fórmula");
        insertarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarBActionPerformed(evt);
            }
        });
        getContentPane().add(insertarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 274, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        atrasB.setText("Atras");
        atrasB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasBActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Formular medicamentos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(atrasB)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(atrasB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/fondo-blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 400, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMBActionPerformed
        // TODO add your handling code here:
        if (isNumeric(cantidadM.getText()) && !(medicamentoCB.getSelectedIndex() == -1)) {
            FormulaMedicamento faux = new FormulaMedicamento();

            String aux = medicamentoCB.getSelectedItem().toString();
            String[] aux2 = aux.split("-");

            faux.setCodigo_medicamento(aux2[0]);
            faux.setCantidad(cantidadM.getText());
            medicamentosS.add(faux);

            Medicamento me = new Medicamento();
            me = controladorMedicamento.consultarMedicamento(aux2[0]);

            Vector u = new Vector();
            u.add(String.valueOf(me.getCodigo_medicamento()));
            u.add(me.getNombre());
            u.add(me.getDescripcion());
            u.add(String.valueOf(me.getCosto()));
            u.add(cantidadM.getText());

            modelo.addRow(u);
            tableM.setModel(modelo);

        } else {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un medicamento", "", JOptionPane.INFORMATION_MESSAGE, null);
        }


    }//GEN-LAST:event_agregarMBActionPerformed

    private void insertarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarBActionPerformed
        // TODO add your handling code here:
        if (validar()) {
            Formula fo = new Formula();

            fo.setIdentificacionEmpleado(Integer.valueOf(usuarioActual.getLogin()));

            fo.setIdentificacionPaciente(Integer.valueOf(idPaciente.getText()));
            System.out.println("recoger datos");
            boolean resul = controladorFormula.insertarFormula(fo);
            if (resul) {
                boolean res = añadirFormulaMedicamentos();
                if (res) {
                    JOptionPane.showMessageDialog(this, "Se agrego la formula a la base de datos", "Mensaje", JOptionPane.INFORMATION_MESSAGE, null);
                    ventanaMedico = new InterfazMedico(usuarioActual);
                    ventanaMedico.setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Hubo un error al agregar la formula ", "", JOptionPane.INFORMATION_MESSAGE, null);
                }
            } else {

                JOptionPane.showMessageDialog(this, "Hubo un error al agregar la formula ", "", JOptionPane.INFORMATION_MESSAGE, null);
            }
        }


    }//GEN-LAST:event_insertarBActionPerformed

    private boolean añadirFormulaMedicamentos() {
        boolean resultado = true;
        String codFormula = controladorFormula.consultarUltimaFormula();
        for (int i = 0; i < medicamentosS.size(); i++) {
            FormulaMedicamento aux = medicamentosS.get(i);
            aux.setCodigo_formula(codFormula);
            boolean res = controladorFormulaMedicamento.insertarFormulaMedicamento(aux);
            if (!res) {
                resultado = false;
            }
        }
        return resultado;
    }

    private void atrasBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasBActionPerformed
        // TODO add your handling code here:
        ventanaMedico = new InterfazMedico(usuarioActual);
        ventanaMedico.setVisible(true);
        dispose();
    }//GEN-LAST:event_atrasBActionPerformed

    private boolean isNumeric(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    private boolean validar() {
        boolean resultado = true;

        
        if (idPaciente.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Verifique los campos", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }
        if(!isNumeric(idPaciente.getText())){
            JOptionPane.showMessageDialog(this, "La identificacion del paciente debe ser un dato numerico", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }
        if(controladorPaciente.consultarPaciente(idPaciente.getText()) == null){
            JOptionPane.showMessageDialog(this, "El paciente no se encuentra en la base de datos", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }
        if (medicamentosS.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe añadir medicamentos a la formula", "", JOptionPane.INFORMATION_MESSAGE, null);
            resultado = false;
            return resultado;
        }
        //Verificar que exista el paciente
        return resultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarMB;
    private javax.swing.JButton atrasB;
    private javax.swing.JTextField cantidadM;
    private javax.swing.JTextField idPaciente;
    private javax.swing.JButton insertarB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> medicamentoCB;
    private javax.swing.JTable tableM;
    // End of variables declaration//GEN-END:variables
}
