/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controlador.ControladorArea;
import controlador.ControladorAsignacion;
import controlador.ControladorCama;
import java.util.ArrayList;
import static javax.management.Query.and;
import javax.swing.JOptionPane;
import logica.Asignacion;
import logica.Cama;

/**
 *
 * @author Alexandra
 */
public class InterfazAsignarCamas extends javax.swing.JFrame {

    private ControladorArea controlArea;

    /**
     * Creates new form InterfazAsignarCamas
     */
    public InterfazAsignarCamas() {
        initComponents();
        controlArea = new ControladorArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        codigo_areas = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Identificacion paciente:");

        codigo_areas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Actualice las Areas" }));
        codigo_areas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                codigo_areasItemStateChanged(evt);
            }
        });
        codigo_areas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigo_areasActionPerformed(evt);
            }
        });

        jLabel2.setText("Codigo area:");

        jLabel3.setText("Camas disponibles:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un area" }));

        jButton1.setText("Asignar Cama");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Actualizar Areas");
        jButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jButton2ItemStateChanged(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo_areas, 0, 188, Short.MAX_VALUE)
                            .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_areas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        codigo_areas.removeAllItems();
        ArrayList<String> ve = new ArrayList<String>();
        ve = controlArea.retornarAreas();
        codigo_areas.addItem("Seleccionar:");

        for (int i = 0; i < ve.size() - 1; i += 2) {
            String item;
            item = ve.get(i) + "," + ve.get(i + 1);
            codigo_areas.addItem(item);
            item = "";
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        System.out.println("VALIDAR QUE EXISTA USUARIO");
        System.out.println("VALIDAR QUE NO EXISTA UNA ASIGNACION");

        try {
            String codigo = this.codigo_areas.getSelectedItem().toString();
            String[] cod = codigo.split(",");
            int areaSeleccionada = Integer.parseInt(cod[0]);
            int numeroCama = Integer.valueOf(jComboBox2.getSelectedItem().toString());
            int idpaciente = Integer.valueOf(jTextField1.getText());

            Asignacion a = new Asignacion();
            a.setIdentificacionPaciente(idpaciente);
            a.setNumeroCama(numeroCama);

            ControladorAsignacion controladorAsignacion = new ControladorAsignacion();
            boolean res = controladorAsignacion.insertarAsignacion(a);

            if (res) {
                JOptionPane.showMessageDialog(this, "Asignacion agregada correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Asignacion no se pudo agregar", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Verifica que la identificacion sea solo numerica o que hayas seleccionado el area y la cama", "Error", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void codigo_areasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_codigo_areasItemStateChanged
        // TODO add your handling code here:
        System.out.println(codigo_areas.getSelectedIndex());
        if (codigo_areas.getSelectedIndex() != 0 && codigo_areas.getSelectedIndex() !=-1) {
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Seleccionar:");
            ControladorCama controladorCama = new ControladorCama();
            ArrayList<Cama> camas = new ArrayList<Cama>();

            String codigo = this.codigo_areas.getSelectedItem().toString();
            String[] cod = codigo.split(",");
            int areaSeleccionada = Integer.parseInt(cod[0]);

            camas = controladorCama.traerTodasCamasActivasLibresPorArea(areaSeleccionada);
            for (int i = 0; i < camas.size(); i++) {
                jComboBox2.addItem(String.valueOf(camas.get(i).getNumeroCama()));
            }
        }else{
            jComboBox2.removeAllItems();
            jComboBox2.addItem("Seleccione un area");
        }
    }//GEN-LAST:event_codigo_areasItemStateChanged

    private void codigo_areasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigo_areasActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_codigo_areasActionPerformed

    private void jButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jButton2ItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAsignarCamas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAsignarCamas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAsignarCamas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAsignarCamas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAsignarCamas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> codigo_areas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
