/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import logica.*;
/**
 *
 * @author jdtorres
 */
public class InterfazAdministrador extends javax.swing.JFrame {

    AgregarEmpleados ventanaAgregar;
    AgregarAreas ventanaAgregarArea;
    ModificarArea ventanaModificarArea;
    Usuario usuarioActual;
    AgregarMedicamentos agregarMedicamentos;
    ModificarMedicamentos modificarMedicamentos;

    /**
     * Creates new form InterfazAdmin
     */
    public InterfazAdministrador() {
        initComponents();
        ventanaAgregarArea = new AgregarAreas();
        ventanaModificarArea = new ModificarArea();
    }
    public InterfazAdministrador(Usuario usuario) {
        initComponents();
        ventanaAgregarArea = new AgregarAreas();
        ventanaModificarArea = new ModificarArea();
        usuarioActual = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarMedicamentosB = new javax.swing.JButton();
        modificarMedicamentosB = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        agregarUsuarioB = new javax.swing.JButton();
        areasButton = new javax.swing.JButton();
        modificarAB = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarMedicamentosB.setText("Agregar medicamentos");
        agregarMedicamentosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMedicamentosBActionPerformed(evt);
            }
        });
        getContentPane().add(agregarMedicamentosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 160, -1));

        modificarMedicamentosB.setText("Modificar medicamentos");
        modificarMedicamentosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMedicamentosBActionPerformed(evt);
            }
        });
        getContentPane().add(modificarMedicamentosB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 160, -1));

        jButton2.setText("Agregar / Modificar Camas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 160, -1));

        agregarUsuarioB.setText("Agregar usuario");
        agregarUsuarioB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarUsuarioBActionPerformed(evt);
            }
        });
        getContentPane().add(agregarUsuarioB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, -1));

        areasButton.setText("Areas");
        areasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areasButtonActionPerformed(evt);
            }
        });
        getContentPane().add(areasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 160, -1));

        modificarAB.setText("Modificar areas");
        modificarAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarABActionPerformed(evt);
            }
        });
        getContentPane().add(modificarAB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 160, -1));

        jButton1.setText("Modificar usuario");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 160, -1));

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Administrador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/images/fondo-blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarUsuarioBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarUsuarioBActionPerformed
        // TODO add your handling code here:

        ventanaAgregar = new AgregarEmpleados();
        System.out.println("abrir ventana");
        ventanaAgregar.setVisible(true);
        System.out.println("cerar ventana");
        this.dispose();

    }//GEN-LAST:event_agregarUsuarioBActionPerformed

    private void areasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areasButtonActionPerformed
        // TODO add your handling code here:
        ventanaAgregarArea.setVisible(true);
        dispose();
    }//GEN-LAST:event_areasButtonActionPerformed

    private void modificarABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarABActionPerformed
        // TODO add your handling code here:
        ventanaModificarArea.setVisible(true);
        dispose();
    }//GEN-LAST:event_modificarABActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ModificarUsuario u= new ModificarUsuario();
        u.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void agregarMedicamentosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMedicamentosBActionPerformed
        // TODO add your handling code here:
        agregarMedicamentos = new AgregarMedicamentos(usuarioActual);
        agregarMedicamentos.setVisible(true);
        dispose();
    }//GEN-LAST:event_agregarMedicamentosBActionPerformed

    private void modificarMedicamentosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMedicamentosBActionPerformed
        // TODO add your handling code here:
        modificarMedicamentos = new ModificarMedicamentos(usuarioActual);
        modificarMedicamentos.setVisible(true);
        dispose();
    }//GEN-LAST:event_modificarMedicamentosBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        InterfazCama i = new InterfazCama(usuarioActual);
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarMedicamentosB;
    private javax.swing.JButton agregarUsuarioB;
    private javax.swing.JButton areasButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarAB;
    private javax.swing.JButton modificarMedicamentosB;
    // End of variables declaration//GEN-END:variables
}
